export const types = Object.freeze({
  // Sync
  PERSON_START_FETCHING: 'PERSON_START_FETCHING',
  PERSON_STOP_FETCHING: 'PERSON_STOP_FETCHING',
  PERSON_FILL: 'PERSON_FILL',
  PERSON_SET_FETCHING_ERROR: 'PERSON_SET_FETCHING_ERROR',

  // Async
  PERSON_FETCH_ASYNC: 'PERSON_FETCH_ASYNC'

});
