export const types = Object.freeze({
  // Sync
  FILM_START_FETCHING: 'FILM_START_FETCHING',
  FILM_STOP_FETCHING: 'FILM_STOP_FETCHING',
  FILM_FILL: 'FILM_FILL',
  FILM_SET_FETCHING_ERROR: 'FILM_SET_FETCHING_ERROR',

  // Async
  FILM_FETCH_ASYNC: 'FILM_FETCH_ASYNC'

});
