export const types = Object.freeze({
  // Sync
  FILMS_START_FETCHING: 'FILMS_START_FETCHING',
  FILMS_STOP_FETCHING: 'FILMS_STOP_FETCHING',
  FILMS_FILL: 'FILMS_FILL',
  FILMS_SET_FETCHING_ERROR: 'FILMS_SET_FETCHING_ERROR',

  // Async
  FILMS_FETCH_ASYNC: 'FILMS_FETCH_ASYNC'

});
