export const SET_ACTIVE_DAY = 'SET_ACTIVE_DAY';
export const SET_FILTER_STATE = 'SET_FILTER_STATE';
export const SET_TOGGLER_STATE = 'SET_TOGGLER_STATE';
export const FILTER_FORECAST = 'FILTER_FORECAST';
